version: '3.9'

x-containers: &container
    restart: ${RESTART_POLICY:-always}
    env_file:
        - .env
    networks:
        - admin_cms-network

services:
    nginx:
        <<: *container
        image: nginx:alpine
        ports:
            - '${APP_PORT_FORWARD:-80}:80'
        volumes:
            - .:/www/app
            - './docker/config/nginx/default.${APP_BUILD_TARGET:-development}.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - php

    php:
        <<: *container
        build:
            context: .
            dockerfile: ./docker/images/php/Dockerfile
            target: ${APP_BUILD_TARGET:-development}
        volumes:
            - /www/app/vendor
            - .:/www/app

networks:
    admin_cms-network:
        name: admin_cms_network
